# Generated by Django 4.2.1 on 2023-05-11 09:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Izdelie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('sku', models.CharField(max_length=255, null=True, verbose_name='Артикул')),
                ('serial_number', models.CharField(max_length=255, null=True, verbose_name='Серийный номер')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Кол-во на остатке')),
                ('image', models.FileField(blank=True, null=True, upload_to='product/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.category')),
                ('izdelie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.izdelie')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='data.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Кол-во')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Просхождение')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='data.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRemove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Кол-во')),
                ('text', models.TextField(blank=True, null=True, verbose_name='КУДА СПИСЫВАЕТСЯ')),
                ('is_remove', models.BooleanField(default=False, verbose_name='ДА\\НЕТ, для списания потерь')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removes', to='data.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.subcategory'),
        ),
    ]
