# Generated by Django 4.2.1 on 2023-05-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr',
            field=models.FileField(blank=True, null=True, upload_to='product/qr/'),
        ),
    ]
