# Generated by Django 4.2.1 on 2023-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_product_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_scan',
            field=models.FileField(blank=True, null=True, upload_to='product/qrscan/'),
        ),
    ]
